version: "3"
services:
    fiware-cef:
        container_name: fiware-cef
        hostname: cef
        image: flopez/fiware-cef:1.1.0
        volumes:
            - ./jirasync.db:/opt/fiware-cef/jirasync.db
            - ./jirasync.ini:/etc/init.d/jirasync.ini
        deploy:
            resources:
                limits:
                    cpus: '0.3'
                    memory: 50M
                reservations:
                    cpus: '0.05'
                    memory: 20M
        logging:
            options:
                max-size: "100m"
                max-file: "5"
